#!/bin/sh
set -e

# Xcode Cloud only clones the git repository — node_modules is gitignored
# (as normal), but CapApp-SPM's Package.swift references Capacitor plugins
# by a relative path *inside* node_modules (@capacitor/push-notifications,
# @capacitor-community/fcm), so those packages can't resolve until
# node_modules actually exists. This script restores it before Xcode
# attempts to resolve Swift Package dependencies.

# Xcode Cloud runs ci_post_clone.sh with CWD set to this script's own
# directory (ios/App/ci_scripts), not the repo root — and CI_WORKSPACE
# turned out to be empty in practice (cd "" is a silent no-op in sh, which
# is why earlier attempts relying on it never actually moved anywhere).
# Navigate to the repo root relative to this script's known location
# instead, so it doesn't depend on any environment variable at all.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
cd "$REPO_ROOT"
echo "--- debug: REPO_ROOT=$REPO_ROOT ---"
pwd
ls -la ios

if ! command -v npm >/dev/null 2>&1; then
  brew install node
fi

npm ci

# ios/App/App/public, config.xml, and capacitor.config.json are all
# generated by the web build + `cap sync` — normally run locally before
# committing, but Xcode Cloud only clones raw source, so generate them here.
npm run build
npx cap sync ios

# GoogleService-Info.plist is a real secret (Firebase API keys) and is
# intentionally gitignored, so it doesn't exist in this clone at all.
# App Store Connect's Xcode Cloud environment variables only accept text
# (no file upload), so GOOGLE_SERVICE_INFO_PLIST holds the file's contents
# base64-encoded as a secret text variable — decode it back into the exact
# path the Xcode project references.
if [ -n "$GOOGLE_SERVICE_INFO_PLIST" ]; then
  echo "$GOOGLE_SERVICE_INFO_PLIST" | base64 -d > "$REPO_ROOT/ios/App/GoogleService-Info.plist"
else
  echo "warning: GOOGLE_SERVICE_INFO_PLIST env var not set — build will fail on Copy GoogleService-Info.plist"
fi
